### ISSUE TITLE
Use http_build_query for query strings

### ISSUE THREAD

**Issue by shadowhand** [TheNetworg/oauth2-azure#1]
This code should [be using `http_build_query`](https://github.com/TheNetworg/oauth2-azure/blob/c7fb53189930bd7f4d96427441ada1a4bcb3b19a/src/Provider/Azure.php#L88-L89).

**Comment by hajekj** [comment]
I don't think this can be done due to the nature of Azure Graph API - for example, when using pagination in their API (using odata) where the returned `odata.nextLink` link can look like this:
`directoryObjects/$/Microsoft.WindowsAzure.ActiveDirectory.User?$skiptoken=X'44537074020001000000213A41646D696E34404772617068446972312E6F6E6D6963726F736F66742E636F6D29557365725F31353365353064662D653930382D343836652D383133622D306335646566313666323334B900000000000000000000'` I don't think it would be a good case to use `http_build_query` here to append the version of API used.

**Comment by hajekj** [comment]
I don't believe that this can be done due to the nature of Graph API using OData, especially in the case where pagination using `odata.nextLink` is used. The format of the link can be following: `directoryObjects/$/Microsoft.WindowsAzure.ActiveDirectory.User?$skiptoken=X'44537074020001000000213A41646D696E34404772617068446972312E6F6E6D6963726F736F66742E636F6D29557365725F31353365353064662D653930382D343836652D383133622D306335646566313666323334B900000000000000000000'` and I think that building the query (adding parameter `api_version` there) using `http_build_query` wouldn't do any good.
