### ISSUE TITLE
Hardcoded URL in Tenant Data

### ISSUE THREAD

**Issue by brianfreytag** [TheNetworg/oauth2-azure#78]
I understand that you are currently working on openid configuration type stuff for v2.0.0 in #21 but do you think there is any way we can get a parameter, or an option or something in the current code that will allow us to change the URL for the tenant details?

Currently in `Azure::getTenantDetails`, the URL `https://login.windows.net/` is hardcoded, so when I authorize and receive an id_token and code via OpenID Connect (https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc), creating the `AccessToken` breaks because the issuers don't match, since the issuer is `https://login.microsoftonline.com/{tenant}/v2.0`. 

It'd be nice to have an extra parameter that one could set to change that URL to the `login.microsoftonline.com/{tenant}/v2.0/.well-known/openid-configuration`.

**Comment by hajekj** [comment]
Absolutely. Do you think you could make a PR to implement the `$instance` property? I think it is safe to set it to `https://login.microsoftonline.com` by default since there is no benefit of using `login.windows.net` endpoint. There will need to be some replacement made as well, so that it keeps working with `common` endpoint, tenant endpoint and `v2.0` common and end tenant endpoints.
